name: Move Tmp Files to Data And Update Index

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'imas-tools/gakuen-adapted-translation-data'
    permissions:
      contents: write

    steps:

    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Install dependencies
      run: pip install -r ./requirements.txt

    - name: Move files
      run: |
        python scripts/move.py

    - name: Update index
      run: python scripts/gen_index.py

    - name: Commit changes
      id: asset-auto-commit-action
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Move tmp files to data and update index"
